import os
import requests
import json
import logging

logger = logging.getLogger(__name__)

# Load from env
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")  
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
DEPLOYMENT_NAME = os.getenv("AZURE_DEPLOYMENT_NAME")  

def generate_followup(subject: str, body: str, category: str, number_of_followups: int) -> list[str]:
    prompt = f"""
You are an expert cold email assistant.

A user wrote this email in the category of "{category}":

Subject: {subject}
Body: {body}

Generate exactly {number_of_followups} follow-up emails.

Each follow-up should:
- Be polite, warm, human generic, and professional
- Reference the initial email’s intent naturally
- Be 1–2 short sentences
- Encourage a response
- Avoid phrases like “just following up” or “greetings” or anything that sounds autogenerated
- Do not write short email closing or email sign-off with name at the end

### Output Format:
Respond strictly as a JSON array of strings. No extra commentary or markdown.

Example:
[
  "Follow-up 1 message here.",
  "Follow-up 2 message here.",
  "Follow-up 3 message here.",
  "Follow-up 4 message here."
]
"""

    headers = {
        "Content-Type": "application/json",
        "api-key": AZURE_OPENAI_API_KEY,
    }

    url = f"{AZURE_OPENAI_ENDPOINT}/openai/deployments/{DEPLOYMENT_NAME}/chat/completions?api-version=2024-12-01-preview"

    data = {
        "messages": [
            {"role": "system", "content": "You are a helpful and professional cold email assistant."},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.7,
        "max_tokens": 500,
    }

    response = requests.post(url, headers=headers, json=data)

    if response.status_code != 200:
        logger.error(f"OpenAI API error: {response.status_code} - {response.text}")
        raise Exception(f"OpenAI API error: {response.status_code} - {response.text}")

    result = response.json()
    text = result['choices'][0]['message']['content'].strip()
    
    try:
        followups = json.loads(text)

        if not isinstance(followups, list):
            raise ValueError("Expected a JSON array but got a different structure.")

        cleaned = [f.strip() for f in followups if isinstance(f, str)]

        if len(cleaned) != number_of_followups:
            raise ValueError(
                f"Expected {number_of_followups} follow-ups, but got {len(cleaned)} valid strings."
            )

        return cleaned

    except Exception as e:
        logger.error(f"[GPT JSON Parse Error] {e}\nRaw GPT output:\n{text}")
        raise Exception(f"[GPT JSON Parse Error] {e}\nRaw GPT output:\n{text}")
