"""add mail_attachments table true  update

Revision ID: 49c813378745
Revises: c6623a852620
Create Date: 2025-08-09 13:17:13.370594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c813378745'
down_revision: Union[str, Sequence[str], None] = 'c6623a852620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mail_attachments', 'gmail_attachment_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mail_attachments', 'part_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mail_attachments', 'part_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mail_attachments', 'gmail_attachment_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
