"""Added new col

Revision ID: 55a37b5d5d65
Revises: 7a03ea9f0f2d
Create Date: 2025-10-04 23:46:06.495354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a37b5d5d65'
down_revision: Union[str, Sequence[str], None] = '7a03ea9f0f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('sender_email', sa.String(), nullable=False))
    op.create_index(op.f('ix_subscribers_sender_email'), 'subscribers', ['sender_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_sender_email'), table_name='subscribers')
    op.drop_column('subscribers', 'sender_email')
    # ### end Alembic commands ###
