"""Add is_attachment to Mail

Revision ID: 6d10027fcec6
Revises: f5a81ffca7c3
Create Date: 2025-07-18 02:15:12.937132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d10027fcec6'
down_revision: Union[str, Sequence[str], None] = 'f5a81ffca7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('mails', sa.Column('is_attachment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('mails', 'is_attachment')

    # ### end Alembic commands ###
