"""Add subscribers relationship to User

Revision ID: 7a03ea9f0f2d
Revises: 70d272011fe8
Create Date: 2025-10-04 23:18:31.884316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a03ea9f0f2d'
down_revision: Union[str, Sequence[str], None] = '70d272011fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
