"""add notifications table

Revision ID: d4138935d2a2
Revises: 6d10027fcec6
Create Date: 2025-07-19 23:42:40.814244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4138935d2a2'
down_revision: Union[str, Sequence[str], None] = '6d10027fcec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 💡 Replace the VARCHAR with Enum in followups.status with explicit cast
    op.execute("""
        ALTER TABLE followups
        ALTER COLUMN status
        TYPE mail_status_enum
        USING status::mail_status_enum
    """)

    # 💡 Replace the VARCHAR with Enum in mails.status with explicit cast
    op.execute("""
        ALTER TABLE mails
        ALTER COLUMN status
        TYPE mail_status_enum
        USING status::mail_status_enum
    """)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mails', 'status',
               existing_type=sa.Enum('scheduled', 'sent', 'failed', 'blocked_by_reply', 'completed', 'done', name='mail_status_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('followups', 'status',
               existing_type=sa.Enum('scheduled', 'sent', 'failed', 'blocked_by_reply', 'completed', 'done', name='mail_status_enum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
