"""update campgains table

Revision ID: eecd2721ea57
Revises: cc0b38faa09c
Create Date: 2025-12-29 21:24:41.019007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eecd2721ea57'
down_revision: Union[str, Sequence[str], None] = 'cc0b38faa09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('subject', sa.String(), nullable=False))
    op.add_column('campaigns', sa.Column('body', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'body')
    op.drop_column('campaigns', 'subject')
    # ### end Alembic commands ###
